### ISSUE TITLE
Basic 64-bit support

### ISSUE THREAD

**Issue by iamgreaser** [LeComm/vxw-client#1]
I'm working on this and will be able to get you a patch, but not until this linker error is fixed:

```
[ben@sas aof-client]$ ./compile
main.o: In function `_D2ui11Check_InputFZv':
/home/ben/Downloads/aof-client/ui.d:131: undefined reference to `_D8derelict4sdl25types9SDL_Event6__initZ'
collect2: error: ld returned 1 exit status
--- errorlevel 1
```

Basically, what you thought was `uint` was, in a lot of cases, `size_t`... which is `ulong` on 64-bit systems.

**Comment by xtreme8000** [comment]
We are aware of this and are working on a solution asap.

**Comment by iamgreaser** [comment]
Nice to see a bit of activity again.

I no longer have the patch handy. But for the most part it boils down to using `size_t` when it says `size_t` rather than using `uint`.

**Comment by LeComm** [comment]
I'm regularly checking the code for conflicts between size_t and uint now. If at all, you will mostly only find a few cases overlooked by me where D refuses to implicitely cast ulong to uint. The formal problems have been solved, now it's all about making it all not segfault.

**Comment by LeComm** [comment]
Compiles and runs on 64 bit systems with Voxlap renderer now.
