### ISSUE TITLE
Segfault after map load.

### ISSUE THREAD

**Issue by agrecascino** [LeComm/vxw-client#2]
Using voxlap renderer.

![screenshot_2017-05-13_11-51-52](https://cloud.githubusercontent.com/assets/9344554/26026947/4b12b7ec-37d3-11e7-874c-90adb36b9499.png)

**Comment by LeComm** [comment]
Currently, Voxlap isn't supported in 64 bit mode, only in 32 bit mode. However, still thanks for the traceback, I did some changes to vxwclient-voxlap-renderer that I expect to have fixed this specific bug and a few others too.

**Comment by LeComm** [comment]
Compiles and runs on 64 bit systems with Voxlap renderer now.
